apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swissknife.fullname" . }}-config
  labels:
    {{- include "swissknife.labels" . | nindent 4 }}
data:
  production.toml: |-
  {{- range .Values.swissknifeConfig }}
    {{ . }}
  {{- end }}

