apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rtl.fullname" . }}-config
  labels: 
  {{- include "rtl.labels" . | nindent 4 }}
data:
  RTL-Config.json: |
    {
      "port": "3000",
      "defaultNodeIndex": 1,
      "dbDirectoryPath": "{{ .Values.rtlConfig.dbDirectoryPath }}",
      "SSO": {
        "rtlSSO": 0,
        "rtlCookiePath": "",
        "logoutRedirectLink": ""
      },
      "nodes": [
        {
          "index": 1,
          "lnNode": "NumeraireSwissknife",
          "lnImplementation": "CLN",
          "Authentication": {
            "runePath": "{{ .Values.rtlConfig.runePath }}"
          },
          "Settings": {
            "userPersona": "OPERATOR",
            "themeMode": "NIGHT",
            "themeColor": "PURPLE",
            "bitcoindConfigPath": "",
            "logLevel": "{{ .Values.rtlConfig.loglevel }}",
            "fiatConversion": false,
            "unannouncedChannels": false,
            "lnServerUrl": "{{ .Values.rtlConfig.lnServerUrl }}"
          }
        }
      ]
    }
