{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lightningd.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{.Values.lspdService.host}}
    secretName: {{.Values.lspdService.secretName}}
  rules:
  - host: {{.Values.lspdService.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "lightningd.fullname" . }}-lspd
            port:
              number: {{.Values.lspdService.port}}
{{- end }}
