{{- if eq (include "lightningd.fullname" .) "lightningd" }}
apiVersion: v1
kind: Secret
metadata:
  name: network
  labels:
    {{- include "lightningd.labels" . | nindent 4 }}
stringData:
  network: {{.Values.global.network}}
{{- end }}
