apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightningd.fullname" . }}
  labels: 
    {{- include "lightningd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.restService.type }}
  ports:
    - port: {{ .Values.restService.port }}
      targetPort: {{ .Values.restService.targetPort }}
      name: rest
      protocol: TCP
  selector:
    {{- include "lightningd.selectorLabels" . | nindent 4 }}
