apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightningd.fullname" . }}-lspd
  labels: 
    {{- include "lightningd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lspdService.type }}
  {{- if and (eq .Values.lspdService.type "LoadBalancer") (.Values.lspdService.staticIP) }}
  loadBalancerIP: {{ .Values.lspdService.staticIP }}
  {{- end }}
  ports:
    - port: {{ .Values.lspdService.port }}
      targetPort: {{ .Values.lspdService.targetPort }}
      name: lspd
      protocol: TCP
  selector:
    {{- include "lightningd.selectorLabels" . | nindent 4 }}
