apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightningd.fullname" . }}
  labels: 
    {{- include "lightningd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: p2p
  selector:
    {{- include "lightningd.selectorLabels" . | nindent 4 }}
