apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightningd.fullname" . }}-p2p
  labels: 
    {{- include "lightningd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.p2pService.type }}
  {{- if and (eq .Values.p2pService.type "LoadBalancer") (.Values.p2pService.staticIP) }}
  loadBalancerIP: {{ .Values.p2pService.staticIP }}
  {{- end }}
  ports:
    - port: {{ .Values.p2pService.port }}
      targetPort: {{ .Values.p2pService.targetPort }}
      name: p2p
      protocol: TCP
  selector:
    {{- include "lightningd.selectorLabels" . | nindent 4 }}
