apiVersion: v1
kind: ConfigMap
metadata:
  name: start-script
data:
  start.sh: |
    #!/bin/sh

    # Read nodes.json content and export it as an environment variable
    export NODES=$(cat /etc/nodes/nodes.json)

    sleep 30

    # Start lspd
    chmod +x /root/.lightning/lspd/lspd
    /root/.lightning/lspd/lspd
