apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitcoin-exporter
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: bitcoind
  namespaceSelector:
    matchNames:
      - bitcoin-mainnet 
  endpoints:
    - port: metrics
      interval: 60s
      path: "/"
