name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      - development

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    name: Lint Helm Charts
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: "latest"
      - name: Lint Helm Charts
        run: |
          helm lint charts/*

  deploy:
    runs-on: ubuntu-latest
    needs: lint-helm
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Configure kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: "latest"
      - name: Add prometheus-community Helm repository
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - name: Update Helm repositories
        run: helm repo update
      - name: Deploy Mainnet
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 55.7.0 --namespace kube-prometheus-stack --values charts/monitoring/values.yaml
          helm upgrade --install cert-manager charts/networking --namespace cert-manager --set cert-manager.enabled=true,ingress-nginx.enabled=false
          helm upgrade --install ingress-nginx charts/networking --namespace ingress-nginx --set cert-manager.enabled=false,ingress-nginx.enabled=true
          helm upgrade --install bitcoind charts/bitcoind/ -f charts/bitcoind/values.yaml --namespace bitcoin-mainnet --create-namespace
          helm upgrade --install lightningd charts/lightningd/ -f charts/lightningd/values.yaml --namespace lightning-mainnet --create-namespace
      - name: Deploy Testnet
        if: github.ref == 'refs/heads/development'
        run: |
          helm upgrade --install bitcoind charts/bitcoind/ -f charts/bitcoind/testnet-values.yaml --namespace bitcoin-testnet --create-namespace
          # Add more Helm upgrade/install commands as needed for other charts
