name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - development

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    name: Lint Helm Charts
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: 'latest'
      - name: Lint Helm Charts
        run: |
          helm lint charts/*

  deploy:
    runs-on: ubuntu-latest
    needs: lint-helm
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Configure kubeconfig
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} 
      - name: Deploy Mainnet
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install bitcoind charts/bitcoind/ -f charts/bitcoind/values.yaml --namespace bitcoin-mainnet --create-namespace
          # Add more Helm upgrade/install commands as needed for other charts
      - name: Deploy Testnet
        if: github.ref == 'refs/heads/development'
        run: |
          helm upgrade --install bitcoind charts/bitcoind/ -f charts/bitcoind/testnet-values.yaml --namespace bitcoin-testnet --create-namespace
          # Add more Helm upgrade/install commands as needed for other charts
