name: Helm CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.3'

    - name: Lint Helm charts
      run: |
        helm lint charts/*

    # Add additional steps for testing your charts here
    # e.g., helm unit tests, integration tests with kind (Kubernetes in Docker)

  # You can add additional jobs for deployment, etc.
